### PR TITLE
Updated report examples and replaced the full example with an image in the README

### PR DESCRIPTION
**Pull request by anna-aleksandrowicz**
Updated report examples and replaced the full example with an image

### CODE REVIEW

**Review by MaorDavidzon — DISMISSED** [review]

**Comment by MarshalX** [comment]
@anna-aleksandrowicz could you pls reupload you image to https://github.com/cycodehq/cycode-cli/tree/main/images? as the others

**Comment by MarshalX** [comment]
lemme provide another img because this one doesnt contain "report url" for docs

**Comment by MarshalX** [comment]
@MaorDavidzon could we merge it without waiting for @anna-aleksandrowicz approve? @saramontif needs new release it ASAP

**Comment by MaorDavidzon** [comment]
> @MaorDavidzon could we merge it without waiting for @anna-aleksandrowicz approve? @saramontif needs it for new release ASAP

Yes it's fine
Let's update the documentation early next week

**Pull request merged**
